USE [master]
GO

/****** Object:  Database [NFL_Database]    Script Date: 12/26/2013 11:13:17 ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'NFL_Database')
DROP DATABASE [NFL_Database]
GO

USE [master]
GO

/****** Object:  Database [NFL_Database]    Script Date: 12/26/2013 11:13:17 ******/
CREATE DATABASE [NFL_Database] ON  PRIMARY 
( NAME = N'NFL_Database', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\NFL_Database.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'NFL_Database_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\NFL_Database_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [NFL_Database] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NFL_Database].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NFL_Database] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NFL_Database] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NFL_Database] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NFL_Database] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NFL_Database] SET ARITHABORT OFF 
GO

ALTER DATABASE [NFL_Database] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [NFL_Database] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [NFL_Database] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NFL_Database] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NFL_Database] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NFL_Database] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NFL_Database] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NFL_Database] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NFL_Database] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NFL_Database] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NFL_Database] SET  DISABLE_BROKER 
GO

ALTER DATABASE [NFL_Database] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NFL_Database] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NFL_Database] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NFL_Database] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NFL_Database] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NFL_Database] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [NFL_Database] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NFL_Database] SET  READ_WRITE 
GO

ALTER DATABASE [NFL_Database] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [NFL_Database] SET  MULTI_USER 
GO

ALTER DATABASE [NFL_Database] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NFL_Database] SET DB_CHAINING OFF 
GO


